### ISSUE TITLE
MockUp -Labyrinth

### ISSUE THREAD

**Issue by Anika1609** [doomsweb/I-CARE-SPIELE#2]
MockUps zum Labyrinth-GUI

**Comment by hielmalki** [comment]
Wie findet ihr meine Lösung?

**Comment by doomsweb** [comment]
@hielmalki finde ich gut. Ich habe es in dem Labyrinth-Spiel schon einigermaßen umgesetzt. Jedoch ohne Spielstände, da wir noch keine Info bekommen haben wie wir genau an die Daten von I-CARE kommen.
