### ISSUE TITLE
Dashboard design

### ISSUE THREAD

**Issue by Anika1609** [doomsweb/I-CARE-SPIELE#6]
Dashboard design + Zusammenhänge aufzeichnen

--> Valentin

**Comment by Anika1609** [comment]
wurde hinfällig, da kein Dashboard benötigt wird

**Comment by hielmalki** [comment]
gemäß Herr Ricken ein Dashboard ist nicht notwendig, es genügt, wenn wir in jeden einzelnen Spiel einen Hinweis geben anhand Mockups Labyrinth.
